### ISSUE TITLE
Acc. of Resnet on Cifar10

### ISSUE THREAD

**Issue by meteozay** [amazon-research/network-deconvolution-pp#2]
Hello,
Thank you for sharing the code.

For Resnet18 and 34 on Cifar 10, I receive the following:
Resnet18: 
Loss: 0.197 | top1: 94.890%, top5: 99.800%, elasped time:   2 seconds. Best Acc: 94.970%
Training finished successfully. Model size:  11173962
Best acc:  94.96999991455078
Resnet18d:
Loss: 0.245 | top1: 94.990%, top5: 99.860%, elasped time:   2 seconds. Best Acc: 94.990%
Training finished successfully. Model size:  11169162
Best acc:  94.98999990234375

The acc. diff. is pretty small compared to those reported. Should we change some params in the experimental analyses?

Thanks.

**Comment by meteozay** [comment]
Improved the acc. with some modifications and updates.

**Comment by yechengxi** [comment]
This accuracy is most likely because deconv is used throughout the whole network.

**Comment by meteozay** [comment]
Thank you for the clarification.

How can I update the code/hyperparameters to reproduce the results given in Table 1 of the previous paper:
https://openreview.net/pdf?id=rkeu30EtvS

Thanks

**Comment by yechengxi** [comment]
Just uploaded a script that we used to generate the commands.
https://github.com/amazon-research/network-deconvolution-pp/blob/main/Classification/gen_cmd.py

**Comment by meteozay** [comment]
Great! 
Thank you very much !!
